### ISSUE TITLE
Get Name and Image data from API

### ISSUE THREAD

**Issue by samjam48** [fac-17/face-name-game#2]
Get a list of names and faces from github

- [x] Take organisation name (and/ or team name)
- [x] Get data on Team / org
- [x] Get data on each member

**Comment by reubengt** [comment]
every team has an id, which can be found from the following endpoint.
https://api.github.com/orgs/{org_name}/teams/{team_name}

the response has an id property

we can then use that id to request for member data

https://api.github.com/teams/{team_id}/members

which gives a list of team members, annoyingly without names.
has a url property which can show the user's data(including name),
individual requests to 

https://api.github.com/users/{username}
